config/routes.rb
Agas::Application.routes.draw do  
  resources :bills

  resources :medical_staffs

  get "home/show"

  get "bill/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "home#show"
  match "/physicians/:id/edit_password", :to =>"physicians#edit_password", :as => "edit_password_physician"
  match "/administrators/:id/edit_password", :to =>"administrators#edit_password", :as => "edit_password_administrator"

  resources :logins
  resources :sessions

  get "sessions/new"
  get "logins/new"
  get "bills/new"

  resources :physicians

  resources :administrators

  resources :patients

  resources :schedules

  resources :appointments

  resources :addresses
  

end

app/models/medical_staff.rb
class MedicalStaff < ActiveRecord::Base
  has_one :login, :as => :owner
  has_one :physician
  has_many :phones, :as => :owner, :dependent => :destroy
  has_many :emails, :as => :owner, :dependent => :destroy
  validates_presence_of :firstname, :lastname, :doc_id

  accepts_nested_attributes_for :login, :allow_destroy => true
  accepts_nested_attributes_for :phones, :allow_destroy => true
  accepts_nested_attributes_for :emails, :allow_destroy => true

end

app/controllers/medical_staffs_controller.rb
class MedicalStaffsController < ApplicationController
  # GET /medical_staffs
  # GET /medical_staffs.json
      helper_method :sort_column, :sort_direction

  def index
    @medical_staffs = MedicalStaff.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @medical_staffs }
      format.xml #index.xml.builder
    end
  end

  # GET /medical_staffs/1
  # GET /medical_staffs/1.json
  def show
    @medical_staff = MedicalStaff.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @medical_staff }
      format.xml #show.xml.builder
    end
  end

  # GET /medical_staffs/new
  # GET /medical_staffs/new.json
  def new
    @medical_staff = MedicalStaff.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @medical_staff }
    end
  end

  # GET /medical_staffs/1/edit
  def edit
    @medical_staff = MedicalStaff.find(params[:id])
  end

  # POST /medical_staffs
  # POST /medical_staffs.json
  def create
    @medical_staff = MedicalStaff.new(params[:medical_staff])

    respond_to do |format|
      if @medical_staff.save
        format.html { redirect_to @medical_staff, :notice => 'Medical staff was successfully created.' }
        format.json { render :json => @medical_staff, :status => :created, :location => @medical_staff }
      else
        format.html { render :action => "new" }
        format.json { render :json => @medical_staff.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /medical_staffs/1
  # PUT /medical_staffs/1.json
  def update
    @medical_staff = MedicalStaff.find(params[:id])

    respond_to do |format|
      if @medical_staff.update_attributes(params[:medical_staff])
        format.html { redirect_to @medical_staff, :notice => 'Medical staff was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @medical_staff.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_staffs/1
  # DELETE /medical_staffs/1.json
  def destroy
    @medical_staff = MedicalStaff.find(params[:id])
    @medical_staff.destroy

    respond_to do |format|
      format.html { redirect_to medical_staffs_url }
      format.json { head :ok }
    end
  end
  
      private
  
  def sort_column
    MedicalStaff.column_names.include?(params[:sort]) ? params[:sort] : "lastname"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/medical_staff_helper.rb
module MedicalStaffHelper
end

app/helpers/medical_staffs_helper.rb
module MedicalStaffsHelper
end

app/views/medical_staffs/_email_fields.html.erb
<%= render :partial => "emails/email_fields", :locals => { :f => f } %>

app/views/medical_staffs/_form.html.erb
<%= nested_form_for(@medical_staff) do |f| %>
  <% if @medical_staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medical_staff.errors.count, "error") %> prohibited this medical_staff from being saved:</h2>

      <ul>
      <% @medical_staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :middlename %><br />
    <%= f.text_field :middlename %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label "Physician" %><br />
    <%= f.select("doc_id", Physician.all.collect {|p| [ "#{p.lastname}, #{p.firstname}", p.id ] }, {:include_blank => 'None'})%>
  </div>
  <% f.object.build_login unless f.object.login %>
   <%= f.fields_for :login do |login| %>
	<%= render :partial => "logins/login_fields",:locals => { :f => login } %> 
   <% end %>

  <%= f.fields_for :phones do |phone|%>
    <%= render"phone_fields", :f => phone%>
  <% end %>
  <p><%= f.link_to_add "Add Phone", :phones%></p>

  <%= f.fields_for :emails do |email| %>
  <%= render "email_fields", :f => email %>
  <% end %>
  <p><%= f.link_to_add "Add Email", :emails %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medical_staffs/_phone_fields.html.erb
<%= render :partial => "phones/phone_fields", :locals => { :f => f } %>

app/views/medical_staffs/edit.html.erb
<% content_for :title, "Editing Medical Staff" %>

<%= render 'form' %>

<%= link_to 'Show', @medical_staff %> |
<%= link_to 'Back', medical_staffs_path %>

app/views/medical_staffs/index.html.erb
<% content_for :title, "Medical Staffers" %>

<table class="index_table">
    <th><%= sortable "firstname", "First Name"%></th>
    <th><%= sortable "lastname", "Last Name"%></th>
    <th>Physician</th>
    <% if(is_admin) %>
    <th colspan="3"><input type="text" size="10" class="defaultText" value="Filter"></th>
    <% else %>
    <th><input type="text" size="10" class="defaultText" value="Filter"></th>
    <% end %>
  </tr>

<% @medical_staffs.each do |medical_staff| %>
<% phys_for_staffer = Physician.find_by_id(medical_staff.doc_id) %>
  <tr class="tr_body">
    <td><%= medical_staff.firstname %></td>
    <td><%= medical_staff.lastname %></td>
    <% if(phys_for_staffer) %>
    <td><%= link_to "#{phys_for_staffer.lastname}, #{phys_for_staffer.firstname}", phys_for_staffer %></td>
    <% else %>
    <td>None</td>
    <% end %>
    <td><%= link_to 'Show', medical_staff %></td>
    <% if is_admin %>
    <td><%= link_to 'Edit', edit_medical_staff_path(medical_staff) %></td>
    <td><%= link_to "&#215;".html_safe, medical_staff, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if(is_admin) %>
<%= link_to 'New Medical staff', new_medical_staff_path %>
<% end %>

app/views/medical_staffs/new.html.erb
<% content_for :title, "New Medical Staff" %>

<%= render 'form' %>

<%= link_to 'Back', medical_staffs_path %>

app/views/medical_staffs/show.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, "Medical Staff" %>

<p>
  <h2>
  <%= "#{@medical_staff.firstname} #{@medical_staff.middlename} #{@medical_staff.lastname} : #{@medical_staff.id}"%>
  </h2>
</p>

<p>
  <b>Physician:</b>
  <% physician = Physician.find_by_id(@medical_staff.doc_id )%>
  <% if (physician) %>
  <%= link_to "#{physician.firstname} #{physician.middlename} #{physician.lastname}", physician %>
  <% else %>
  None
  <% end %>
</p>

  <% @medical_staff.phones.each do  |phone| %>
    <%= render :partial => "phones/show", :locals => {:f => phone}%>
  <% end %>
  <% @medical_staff.emails.each do |email| %>
    <%= render :partial => "emails/show", :locals => {:f => email}%>
  <% end %>

<%= link_to 'Edit', edit_medical_staff_path(@medical_staff) %> |
<%= link_to 'Back', medical_staffs_path %>