config/routes.rb
Agas::Application.routes.draw do  
  resources :bills

  resources :medical_staffs

  get "home/show"

  get "bill/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "home#show"
  match "/physicians/:id/edit_password", :to =>"physicians#edit_password", :as => "edit_password_physician"
  match "/administrators/:id/edit_password", :to =>"administrators#edit_password", :as => "edit_password_administrator"

  resources :logins
  resources :sessions

  get "sessions/new"
  get "logins/new"
  get "bills/new"

  resources :physicians

  resources :administrators

  resources :patients

  resources :schedules

  resources :appointments

  resources :addresses
  

end

app/models/physician.rb
class Physician < ActiveRecord::Base
 has_one :login, :as => :owner
 has_many :addresses, :as => :owner, :dependent => :destroy
 has_many :phones, :as => :owner, :dependent => :destroy
 has_many :emails, :as => :owner, :dependent => :destroy
 has_many :medical_staffs
 has_many :appointments, :foreign_key => 'phy_id'
 validates_presence_of :firstname, :lastname, :specialty, :office_num

 accepts_nested_attributes_for :login, :allow_destroy => true
 accepts_nested_attributes_for :addresses, :allow_destroy => true 
 accepts_nested_attributes_for :phones, :allow_destroy => true 
 accepts_nested_attributes_for :emails, :allow_destroy => true
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_filter :authorize_administrator, :only => [:index, :new, :create, :destroy]
    helper_method :sort_column, :sort_direction

  #If you aren't an admin, you are a physician. AppControl requires a login to begin with.

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @physicians }
      format.xml #index.xml.builder
    end
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
    @physician = Physician.find(params[:id])
    #todo: authorize we are the correct physician.

    respond_to do |format|
      format.html
      format.xml #show.xml.builder
    end
  end

  # GET /physicians/new
  # GET /physicians/new.json
  def new
    @physician = Physician.new
    @physician.build_login
  end

  # GET /physicians/1/edit
  def edit
    @physician = Physician.find(params[:id])
  end
  
  def edit_password
    @physician = Physician.find(params[:id])

  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(params[:physician])

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, :notice => 'Physician was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "new" }
        format.json { render :json => @physician.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /physicians/1
  # PUT /physicians/1.json
  def update
    @physician = Physician.find(params[:id])

    respond_to do |format|
      if @physician.update_attributes(params[:physician])
        format.html { redirect_to @physician, :notice => 'Physician was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @physician.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician = Physician.find(params[:id])
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to physicians_url }
      format.json { head :ok }
    end
  end
  
    private
  
  def sort_column
    Physician.column_names.include?(params[:sort]) ? params[:sort] : "lastname"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_address_fields.html.erb
<%= render :partial => "addresses/address_fields", :locals => { :f => f } %>

app/views/physicians/_avail_times.html.erb
<% avail_times = Appointment.available_future_times(@physician.id, 6) %>
<% paging = Kaminari.paginate_array(avail_times).page(params[:page]).per(15) %>
<table class="index_table">
  <tr>
    <th><%=  "Start Time" %></th>
    <th><%=  "End Time" %></th>
  </tr>

  <% paging.each do |cur_time_block| %>
  <tr class="tr_body">
    <td><%= cur_time_block.start_time.strftime("%m/%d/%Y %I:%M %p") %></td>
    <td><%= cur_time_block.end_time.strftime("%m/%d/%Y %I:%M %p") %></td>
  <tr>
<% end %>
<%= paginate paging %>

</table>

app/views/physicians/_form.html.erb
<%= nested_form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname%><br />
    <%= f.text_field :firstname%>
  </div>
  <div class="field">
    <%= f.label :middlename%><br />
    <%= f.text_field :middlename%>
  </div>
  <div class="field">
    <%= f.label :lastname%><br />
    <%= f.text_field :lastname%>
  </div>
  <div class="field">
    <%= f.label :specialty %><br />
    <%= f.text_field :specialty %>
  </div>
  <div class="field">
    <%= f.label :office_num %><br />
    <%= f.text_field :office_num %>
  </div>
   <%= f.fields_for :login do |login| %>
		<%= render :partial => "logins/login_fields",:locals => { :f => login } %> 
   <% end %>

  <%= f.fields_for :addresses  do |address| %>
     <%= render "address_fields", :f => address %>
  <% end %>
<p><%= f.link_to_add "Add Address", :addresses%></p>

  <%= f.fields_for :phones do |phone|%>
    <%= render"phone_fields", :f => phone%>
  <% end %>
<p><%= f.link_to_add "Add Phone", :phones%></p>

  <%= f.fields_for :emails  %>
<p><%= f.link_to_add "Add Email", :emails %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<% content_for :title, "Editing Physician" %>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %> 

app/views/physicians/edit_password.html.erb
<% content_for :title, "Edit Password Physician" %>

<%= nested_form_for @physician do |f| %>
  <%= f.fields_for :logins do |login| %>
    <%= render :partial => '/logins/login_edit_fields', :locals => { :f => login} %>
  <% end %>
  <%= link_to( "back", edit_physician_path(@physician)) %>
<% end %>

app/views/physicians/index.html.erb
<% content_for :title, "Physicians" %>

<table class="index_table">
  <tr>
    <th><%= sortable "id" %></th>
    <th><%= sortable "lastname", "Last Name" %></th>
    <th><%= sortable "firstname", "First Name"%></th>
    <th><%= sortable "office_num","Office Number"%></th>
    <th><%= sortable "specialty", "Specialty"%></th>
    <th colspan="3"><input type="text" size="10" class="defaultText" value="Filter"></th>
  </tr>

<% @physicians.each do |physician| %>
  <tr class="tr_body">
    <td><%= physician.id %></td>
    <td><%= physician.lastname %></td>
    <td><%= physician.firstname%></td>
    <td><%= physician.office_num %></td>
    <td><%= physician.specialty %></td>
    <td><%= link_to 'Show', physician %></td>
    <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
    <td><%= link_to  "&#215;".html_safe, physician, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<% content_for :title, "New Physician" %>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<% content_for :title, "Physician" %>

<p id="notice"><%= notice %></p>

<p>
  <h2>
    <%= "#{@physician.firstname} #{@physician.middlename} #{@physician.lastname} : #{@physician.id} "%>
  </h2>
</p>
<p>
  <b>Specialty:</b>
  <%= @physician.specialty %>
</p>

<p>
  <b>Office num:</b>
  <%= @physician.office_num %>
</p>

  <% @physician.addresses.each do |address|  %>
    <%= render :partial => "addresses/show", :locals => {:f => address} %>
  <% end %>
  <% @physician.phones.each do  |phone| %>
    <%= render :partial => "phones/show", :locals => {:f => phone}%>
  <% end %>

  <% @physician.emails.each do |email|%>
    <%= render :partial => "emails/show", :locals => {:f => email}%>
  <% end %>

<p>
  <b>Available Times:</b>
  <input type="text" size="10" class="defaultText" value="Filter">
  <%= render "avail_times" %>
</p>

<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>