config/routes.rb
Agas::Application.routes.draw do  
  resources :bills

  resources :medical_staffs

  get "home/show"

  get "bill/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "home#show"
  match "/physicians/:id/edit_password", :to =>"physicians#edit_password", :as => "edit_password_physician"
  match "/administrators/:id/edit_password", :to =>"administrators#edit_password", :as => "edit_password_administrator"

  resources :logins
  resources :sessions

  get "sessions/new"
  get "logins/new"
  get "bills/new"

  resources :physicians

  resources :administrators

  resources :patients

  resources :schedules

  resources :appointments

  resources :addresses
  

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
 paginates_per 15
  validates_presence_of :start_time, :end_time, :phy_id

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :authorize_at_least_medical_staff
  helper_method :sort_column, :sort_direction
  helper_method :available_times

  #Todo: add auth for schedules in individual methods

  # GET /schedules
  # GET /schedules.json
  def index

    if(is_admin)
       @schedules = Schedule.order(sort_column + " " + sort_direction).page(params[:page])
    elsif(is_phys) 
       @schedules = Schedule.where(:phy_id => current_user.id).order(sort_column + " " + sort_direction).page(params[:page])
    elsif(is_medstaff)
       @schedules = Schedule.where(:phy_id => current_user.doc_id).order(sort_column + " " + sort_direction).page(params[:page])
    end
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
     end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, :notice => 'Schedule was successfully created.' }
        format.json { render :json => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, :notice => 'Schedule was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :ok }
    end
  end
  
  private
  
  def sort_column
    Schedule.column_names.include?(params[:sort]) ? params[:sort] : "start_time"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def future_schedules(schedules, months=-1)
    time_in_a_month = 2592000
    time_dilation = time_in_a_month * 12 #Default to a year
    if(months > 0)
      time_dilation = time_in_a_month * months
    end
    ret_schedules = []
    schedules.each do |schedule|
      if(schedule.start_time > (Time.now-86400) && schedule.start_time < (Time.now + time_dilation))
        ret_schedules << schedule
      end
    end
    ret_schedules
  end
  
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :datetimepicker_start, "Start Date/Time" %>
    <%= f.text_field :start_time, {:id => 'schedule_datetimepicker_start'} %>
  </div>
  <div class="field">
    <%= f.label :datetimepicker_end, "End Date and Time" %>
    <%= f.text_field :end_time, {:id => 'schedule_datetimepicker_end'} %>
  </div>
  <div class="field">
    <% #TODO: Pull this out of the session for the currently logged in phys. If this isn't a physician viewing, they shouldn't have access to the page in the first place. %>
    <% if(is_admin) %>
    <%= f.label :phy_id, "Physician" %><br />
    <%= f.select("phy_id", Physician.all.collect {|p| [ "#{p.lastname}, #{p.firstname}", p.id ] }, {:include_blank => 'None'})%>
    <% else %>
    <%= f.hidden_field :phy_id, :value => current_user.id %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<% content_for :title, "Schedules" %>

<table class="index_table">
  <tr>
    <th><%= sortable "start_time", "Start time"%></th>
    <th><%= sortable "end_time", "End time"%></th>
    <th>Physician</th>
    <th colspan="3"><input type="text" size="10" class="defaultText" value="Filter"></th>
  </tr> 

<% #A little logic to determine which appointments to display %>
<% @schedules.each do |schedule| %> 
<% phys_for_sch = Physician.find_by_id(schedule.phy_id) %>
  <tr class="tr_body">
    <td><%= schedule.start_time.strftime("%m/%d/%Y %I:%M %p") %></td>
    <td><%= schedule.end_time.strftime("%m/%d/%Y %I:%M %p") %></td>
    <% if phys_for_sch %>
    <td><%= link_to "#{phys_for_sch.lastname}, #{phys_for_sch.firstname}", phys_for_sch %></td>
    <% else %>
    <td>None</td>
    <% end %>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to "&#215;".html_safe, schedule, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= paginate @schedules %>

<br />

<% if(is_admin || is_phys) %>
<%= link_to 'New Schedule', new_schedule_path %>
<% end %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<% phys_for_sch = Physician.find_by_id(@schedule.phy_id) %>

<p id="notice"><%= notice %></p>

<p>
  <b>Start time:</b>
  <%= @schedule.start_time.strftime("%m/%d/%Y %I:%M %p") %>
</p>

<p>
  <b>End time:</b>
  <%= @schedule.end_time.strftime("%m/%d/%Y %I:%M %p") %>
</p>

<p>
  <b>Phyisican:</b>
  <% if phys_for_sch %>
  <%= link_to "#{phys_for_sch.lastname}, #{phys_for_sch.firstname}", phys_for_sch %>
  <% else %>
  None
  <% end %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>