config/routes.rb
Agas::Application.routes.draw do  
  resources :bills

  resources :medical_staffs

  get "home/show"

  get "bill/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "home#show"
  match "/physicians/:id/edit_password", :to =>"physicians#edit_password", :as => "edit_password_physician"
  match "/administrators/:id/edit_password", :to =>"administrators#edit_password", :as => "edit_password_administrator"

  resources :logins
  resources :sessions

  get "sessions/new"
  get "logins/new"
  get "bills/new"

  resources :physicians

  resources :administrators

  resources :patients

  resources :schedules

  resources :appointments

  resources :addresses
  

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
 has_one :login, :as => :owner
 validates_presence_of :name

 accepts_nested_attributes_for :login, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_filter :authorize_administrator

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @administrators }
    end
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @administrator }
    end
  end

  # GET /administrators/new
  # GET /administrators/new.json
  def new
    @administrator = Administrator.new
    @administrator.build_login

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @administrator }
    end
  end

  # GET /administrators/1/edit
  def edit
    @administrator = Administrator.find(params[:id])
  end

  def edit_password
    @administrator = Administrator.find(params[:id])
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(params[:administrator])

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, :notice => 'Administrator was successfully created.' }
        format.json { render :json => @administrator, :status => :created, :location => @administrator }
      else
        format.html { render :action => "new" }
        format.json { render :json => @administrator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /administrators/1
  # PUT /administrators/1.json
  def update
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      if @administrator.update_attributes(params[:administrator])
        format.html { redirect_to @administrator, :notice => 'Administrator was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @administrator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator = Administrator.find(params[:id])
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url }
      format.json { head :ok }
    end
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= nested_form_for(@administrator) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

   <%= f.fields_for :login do |login| %>
        <%= render :partial => "logins/login_fields",:locals => { :f => login } %>
   <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

  
<% end %>

app/views/administrators/edit.html.erb
<% content_for :title, "Edit Administrators" %>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/edit_password.html.erb
<% content_for :title, "Edit Password Administrator" %>

<%= nested_form_for @administrator do |f| %>
  <%= f.fields_for :login do |login| %>
    <%= render :partial => '/logins/login_edit_fields', :locals => { :f => login} %>
  <% end %>
  <%= link_to( "Back", edit_administrator_path(@administrator)) %>
<% end %>

app/views/administrators/index.html.erb
<% content_for :title, "Administrators" %>

<table class="index_table">
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>

<% @administrators.each do |administrator| %>
  <tr>
    <td><%= administrator.name %></td>
    <% #password stuff? %>
    <td><%= link_to 'Show', administrator %></td>
    <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
    <td><%= link_to 'Destroy', administrator, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<% content_for :title, "New Administrators" %>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<% content_for :title, "Administrator" %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @administrator.name %>
</p>

<% #Maybe a link to change password in here? %>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>